**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [83]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [84]:
# We can do this in a number of ways

x = np.zeros(10).astype(int)
x[4] = 1
print(x)

[0 0 0 0 1 0 0 0 0 0]


In [85]:
x = (np.arange(10)==4).astype(int)
print(x)

[0 0 0 0 1 0 0 0 0 0]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [86]:
#Code here
x = int(input("Enter the number of rows: "))
y = int(input("Enter the number of columns: "))
a = np.random.random((x,y))
print(a)
print("The average of the array is:",a.mean())

Enter the number of rows: 3
Enter the number of columns: 4
[[0.81452904 0.52528884 0.31539383 0.44834677]
 [0.25985011 0.32366044 0.88195383 0.33758963]
 [0.44229265 0.51491394 0.27003994 0.76727119]]
The average of the array is: 0.49176085042937245


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [87]:
#Code here
a = int(input("Enter the number of rows: "))
b = int(input("Enter the number of columns: "))
x = np.ones((a,b)).astype(int)
x[1:-1,1:-1] = 0
print(x)

Enter the number of rows: 4
Enter the number of columns: 4
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [88]:
x = np.linspace(0,1,12,endpoint=False)[1:-1]
print(x)

[0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333]




```
`# This is formatted as code`
```

###`Q-5:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [89]:
#Code here
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


###`Q-6:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [90]:
Z = np.random.random((10,2))
print(Z)
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print("The array of distance of each point:")
print(D)

[[0.07043717 0.66890498]
 [0.95462578 0.46249564]
 [0.85757119 0.97672389]
 [0.09298864 0.82146881]
 [0.84042955 0.38914569]
 [0.87694561 0.13714252]
 [0.46462891 0.02120477]
 [0.42372263 0.85753002]
 [0.77217805 0.09895844]
 [0.44793534 0.38969671]]
The array of distance of each point:
[[0.         0.90796162 0.8451819  0.15422156 0.8192396  0.96603684
  0.75822338 0.40048723 0.90403502 0.46953395]
 [0.90796162 0.         0.52330706 0.93342396 0.13572396 0.33449793
  0.65941987 0.66174793 0.40675112 0.51189343]
 [0.8451819  0.52330706 0.         0.78018627 0.58782818 0.83980488
  1.0331604  0.44992416 0.88190939 0.71582291]
 [0.15422156 0.93342396 0.78018627 0.         0.86346464 1.04062049
  0.88234858 0.33269413 0.99162467 0.55894034]
 [0.8192396  0.13572396 0.58782818 0.86346464 0.         0.25463508
  0.52593407 0.62691988 0.29810553 0.39249459]
 [0.96603684 0.33449793 0.83980488 1.04062049 0.25463508 0.
  0.42830669 0.85109883 0.11150904 0.49782872]
 [0.75822338 0.65941987 1.0331

###`Q-7:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [91]:
#Code here
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


### `Q-8:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [92]:
#Code here
x = np.array(input().split(),float)
print(x[::-1])

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### `Q-9:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [93]:
#Code here
x = np.array(input().split(),int)
print("elements_count :",x.size)

1 2 4 76 8
elements_count : 5


### `Q-10:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



4**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [94]:
#Code here
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

### `Q-11:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [95]:
#Coder here
def vertical_stack(*args):
    return np.vstack(args)

In [96]:
xs = np.array([[0, 1, 2 ,3, 4],[5 ,6 ,7 ,8 ,9]])
ys = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
vertical_stack(xs, ys)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### `Q-12:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [97]:
#Code here
def date_array(start, end):
    start = np.datetime64(start)
    end = np.datetime64(end)
    dates = np.arange(start, end+ np.timedelta64(1, 'D'), dtype='datetime64[D]')
    date_strings = dates.astype(str)

    return date_strings

In [98]:
date_array('2020-09-15', '2020-09-25')

array(['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
       '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
       '2020-09-23', '2020-09-24', '2020-09-25'], dtype='<U28')

###`Q-13:` Subtract the mean of each row from a matrix.

In [99]:
#code here
matrix = np.arange(1,10).reshape(3,3)
print(matrix)
print(matrix - matrix.mean(axis=0))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


###`Q-14:` Swap column-1 of array with column-2 in the array.

In [100]:
#Code here
matrix = np.arange(1,10).reshape(3,3)
print(matrix)
matrix[:,[0,1]] = matrix[:,[1,0]]
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 1 3]
 [5 4 6]
 [8 7 9]]


###`Q-15:` Replace odd elements in arrays with -1.

In [101]:
#Code here

In [102]:
array = np.arange(1,10)
array[array % 2 != 0] = -1
print(array)

[-1  2 -1  4 -1  6 -1  8 -1]


###`Q-16:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [103]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
np.maximum(a,b)

array([6, 3, 1, 7, 8])

###`Q-17` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [104]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[6144,   10, 9128, 1802, 7937],
       [2975, 5973, 1505, 7494, 9193],
       [9808, 8907,  626,  276,   26],
       [7483, 3512, 9739, 1039, 1624],
       [8429, 6280, 7146, 4959, 7449],
       [ 308, 3869, 3277, 4053, 3430],
       [ 668, 7898, 5155, 7153, 3630],
       [3962,   24, 2437, 6706, 1832]])

In [105]:
#Code here
print(arr1[:,::2])

[[6144 9128 7937]
 [2975 1505 9193]
 [9808  626   26]
 [7483 9739 1624]
 [8429 7146 7449]
 [ 308 3277 3430]
 [ 668 5155 3630]
 [3962 2437 1832]]


In [82]:
norm_arr = (arr1 - arr1.min()) / (arr1.max() - arr1.min())
print(norm_arr)

[[0.41604267 0.41245256 0.74705098 0.98276746 0.47276644]
 [0.78110575 0.71443225 0.41378603 0.13088522 0.46456047]
 [0.45953431 0.23633193 0.09262488 0.68878859 0.        ]
 [0.03467022 0.26720689 0.41727357 0.90327213 0.33593189]
 [0.67206893 0.1483229  0.88644989 0.00748795 0.10729306]
 [0.87947482 1.         0.40250282 0.07098164 0.41183711]
 [0.18863473 0.53687558 0.41152939 0.45994461 0.63503949]
 [0.73658837 0.20853421 0.56026259 0.53667043 0.58088009]]


###`Q-18:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [114]:
#Code here
def nth_largest(arr, n):
    arr = np.sort(arr)
    return arr[-n]

In [117]:
nth_largest(np.array([12,34,40,7,1,0]), 3)

12

###`Q-19:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [121]:
#code here
a = np.array([1,2,3])
repeated_elements = np.repeat(a,3)
repeated_array = np.tile(a,3)
print(np.concatenate((repeated_elements,repeated_array)))


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
